# Generated by Django 3.2 on 2021-04-25 05:02

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrar_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor do produto')),
                ('qtd', models.IntegerField(blank=True, default=0, verbose_name='Quantidade de produtos')),
                ('status', models.BooleanField(default=False)),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_despesa', models.CharField(max_length=255, verbose_name='Nome da despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total da despesa')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rua', models.CharField(max_length=255, verbose_name='Nome da rua')),
                ('numero_casa', models.CharField(max_length=6, verbose_name='Número da residência')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_itens', models.IntegerField(blank=True, default=0, verbose_name='Quantidade de Itens Vendidos')),
                ('observacao', models.CharField(max_length=255, verbose_name='Descrição da venda')),
                ('data_hora_venda', models.DateTimeField(auto_now_add=True)),
                ('fk_cadastrar_produto', models.ManyToManyField(to='GDS.Cadastrar_produto', verbose_name='Produtos')),
                ('fk_comprador', models.ManyToManyField(to='GDS.Cliente', verbose_name='Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf_funcionario', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('email_funcionario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('codigo_de_contrato', models.CharField(max_length=11, verbose_name='Código do contrato')),
                ('status', models.BooleanField(default=False, verbose_name='Situação')),
                ('fk_funcao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='GDS.funcao', verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão social')),
                ('cnpj', models.CharField(max_length=18, verbose_name='Nome completo')),
                ('email_fornecedo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('observacao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('fk_endereco', models.ManyToManyField(to='GDS.Endereco', verbose_name='Nome da rua e número da empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='fk_endereco',
            field=models.ManyToManyField(to='GDS.Endereco', verbose_name='Nome da rua e número da casa'),
        ),
    ]
