# Generated by Django 3.2 on 2021-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedore',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, max_length=255, verbose_name='Descrição da venda'),
        ),
    ]
