# Generated by Django 3.2 on 2021-06-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDS', '0002_auto_20210527_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO')], max_length=3, verbose_name='Empregado'),
        ),
    ]
